name: 🧠 AI Autopush Workflow

on:
  push:
    branches: [main]
  schedule:
    - cron: '*/15 * * * *' # ⏱️ Every 15 minutes
  workflow_dispatch:

jobs:
  autopush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run AI HealthCheck
        run: node .github/ai-health-check.js

